* flummbot simple irc-bot
Simple IRC-bot I wrote in golang for my irc-channel.

** Current features
  - Authenticate to services
  - Join channels
  - Listen to the command =!tell <person> <message>=
  - Deliver =<message>= to =<person>= the next time =<person>= joins or say something
  - Save quotes with the command =!quote <message>=
  - Tell random quote with the command =!quote=
  - Join channels when requested by being invited. Also got a Whitelist.

** Install dependencies
#+begin_src shell
git submodule init
git submodule update
#+end_src

** Configure the bot
Copy the sample config =flummbot.sample.json= to =flummbot.json= and look
through the following sections.

*** Connection
Change the values of =channel=, =nick=, =server=, =tls= and =message=. You
can also specify =nickservidentify= to set a message to send to NickServ on
connect.

*** Database
=file= specifies file used for sqlite.

*** Tells
=command= specifies command used in the =!tell= module.

*** Quotes
=command= specifies command used in the =!quote= module.

*** Invite
=message= specifies message the bot tells in a channel it got invited to. We
also use =Sprintf= to inject one variable into the string which contains the
nick that invited the bot to the channel. Specify it with =%s= in this
variable.

=whitelist= is a json-list with nicks allowed to invite the bot to other
channels.

** Building the bot
#+begin_src shell
make build
#+end_src

** Starting the bot
I've included a systemd-service file that I use to start my bot.
