---
name: Check

'on': [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
      - run: 'nix fmt . -- --check'
      - run: 'nix flake check'
